name: "test_alignet_proj_lora"

trainer:
  accelerator: gpu
  devices: 1
  precision: 32
  seed: 33

datasets:
  test_1:
    name: val_ssl4eos12_projective
    type: SSL4EOS12CSVDataset
    path: files/test/ssl4eos12_test_affine_projective_pairs_S1_S2_cross_season.csv
    data_path: data/SSL4EO-S12_100patches/
    norm: min-max
    homography: projective
    mode: multi

model:
  model_name: AligNetModel
  architecture: AligNetViT
  input_channels: 1
  img_size: 336
  attention_heads: 4
  window_size: 16
  embed_dim: 1024
  num_transform_parameters: 8
  use_lora: true                  # true / false
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.2

test:
  direction: both                                                         # both / forward / inverse
  num_workers: 3
  checkpoint_path: "checkpoints/proj_imagenet_sat_sensoraug_lora.ckpt"    # "checkpoints/proj_imagenet_sat_sensoraug_lora.ckpt" / "checkpoints/proj_imagenet_sat_sensoraug.ckpt" / "checkpoints/proj_imagenet_lvd_sensoraug.ckpt" / "checkpoints/proj_imagenet_sat_traditionalaug.ckpt" / "checkpoints/proj_imagenet_sat_noaug.ckpt"

  metrics:
    rmse:
      type: calculate_rmse
      better: lower
    mi:
      type: calculate_mi
      better: higher
    h_err:
      type: calculate_h_err
      better: lower
    diff_rmse:
      type: calculate_rmse
      better: lower
    auc:
      type: calculate_mpd
      better: higher
    acc:
      type: calculate_acc
      better: higher
