name: "test_alignet_imagenet_sat"

trainer:
  accelerator: cuda
  devices: 1
  precision: 32
  seed: 33

datasets:
  test_1:
    name: val_dream_affine
    type: DREAMCSVDataset
    path: files/test/dream_test_affine.csv
    data_path: data/DREAM_NPY/
    norm: min-max
    homography: affine
    mode: multi

model:
  model_name: AligNetModel
  architecture: AligNetViT
  input_channels: 1
  attention_heads: 4
  window_size: 16
  embed_dim: 1024
  num_transform_parameters: 6

test:
  num_workers: 3
  checkpoint_path: "./checkpoints/affine_imagenet_sat_sensoraug.ckpt"    # "./checkpoints/affine_imagenet_sat_sensoraug.ckpt" / "./checkpoints/affine_imagenet_lvd_sensoraug.ckpt" / "./checkpoints/affine_imagenet_sat_traditionalaug.ckpt" / "./checkpoints/affine_imagenet_sat_noaug.ckpt"

  metrics:
    rmse:
      type: calculate_rmse
      better: lower
    mpd:
      type: calculate_mpd
      better: lower
    iou:
      type: calculate_iou
      better: higher
    mi:
      type: calculate_mi
      better: higher
    re:
      type: calculate_re
      better: lower
    h_err:
      type: calculate_h_err
      better: lower
