name: "alignet_imagenet_projective_lora"

trainer:
  accelerator: gpu
  devices: 1
  precision: 32    # 32 / 16-mixed
  seed: 33

datasets:
  train_1:
    type: QXSsaroptDataset
    path: files/train/qxssaropt_train.txt
    data_path: data/QXSLAB_SAROPT/
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: multi
    traditional_augmentation: false
    sensor_like_augmentation: false
  train_2:
    type: GeoNRWDataset
    path: files/train/geonrw_train.csv
    data_path: data/GeoNRW/
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: multi
    traditional_augmentation: false
    sensor_like_augmentation: false
  train_3:
    type: ICGCDataset
    path: files/train/icgc_hr_lr_train.csv
    data_path: data/ICGC_HR_LR/
    target_resolution: 5
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: multi
    traditional_augmentation: false
    sensor_like_augmentation: false
  train_4:
    type: ImageNetDataset
    path: files/train/imagenet_train_files.txt
    data_path: data/ImageNet/
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: mono
    use_subset: true
    traditional_augmentation: false
    sensor_like_augmentation: true
  validation_1:
    name: val_mdas_proj_rgb_s1
    type: MDASCSVDataset
    path: files/test/mdas_test_affine_projective_pairs/mdas_test_affine_projective_3K_RGB_Sentinel-1.csv
    data_path: data/MDAS/valid/
    norm: min-max
    homography: projective
    mode: multi
  validation_2:
    name: val_mdas_proj_dsm_s2
    type: MDASCSVDataset
    path: files/test/mdas_test_affine_projective_pairs/mdas_test_affine_projective_3K_DSM_Sentinel-2.csv
    data_path: data/MDAS/valid/
    norm: min-max
    homography: projective
    mode: multi
  validation_3:
    name: val_mdas_proj_30_10
    type: MDASCSVDataset
    path: files/test/mdas_test_affine_projective_pairs/mdas_test_affine_projective_EeteS_EnMAP_30m_EeteS_Sentinel_2_10m.csv
    data_path: data/MDAS/valid/
    norm: min-max
    homography: projective
    mode: multi
  validation_4:
    name: val_qxssaropt_proj
    type: QXSsaroptDataset
    path: files/valid/qxssaropt_valid.txt
    data_path: data/QXSLAB_SAROPT/
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: multi
  validation_5:
    name: val_geonrw_proj
    type: GeoNRWDataset
    path: files/valid/geonrw_valid.csv
    data_path: data/GeoNRW/
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: multi
  validation_6:
    name: val_icgc_proj
    type: ICGCDataset
    path: files/valid/icgc_hr_lr_valid.csv
    data_path: data/ICGC_HR_LR/
    target_resolution: 5
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: multi

model:
  model_name: AligNetModel
  architecture: AligNetViT
  pretrained_encoder_path: "facebook/dinov3-vitl16-pretrain-sat493m"
  img_size: 336
  input_channels: 1
  attention_heads: 4
  window_size: 16
  num_transform_parameters: 8
  project_embed: false
  use_lora: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.2

loss:
  type: RegistrationLoss

train:
  num_workers: 3
  freeze_policy: ~
  batch_size: 70
  epochs: 40
  lr: 0.00001
  momentum: 0.9
  scheduler: ExponentialLR
  scheduler_gamma: 0.99999
  checkpoint_dir: "./experiments"
  checkpoint_path: "checkpoints/proj_imagenet_sat_sensoraug.ckpt"
  checkpoint_interval: 200
  val_interval: 0.2
  log_interval: 50

  losses:
    alpha1: 10
    alpha2: 1
    alpha3: 1

wandb:
  project: alignet
  resume_id: ~
