name: "alignet_imagenet_projective"

trainer:
  accelerator: gpu
  devices: 1
  precision: 32    # 32 / 16-mixed
  seed: 33

datasets:
  train:
    type: ImageNetDataset
    path: files/train/imagenet_train_files.txt
    data_path: data/ImageNet/
    norm: min-max
    homography: affine_projective    # affine / projective / affine_projective
    mode: mono
    traditional_augmentation: false
    sensor_like_augmentation: true
  validation_1:
    name: val_mdas_proj_rgb_s1
    type: MDASCSVDataset
    path: files/test/mdas_test_affine_projective_pairs/mdas_test_affine_projective_3K_RGB_Sentinel-1.csv
    data_path: data/MDAS/valid
    norm: min-max
    homography: projective
    mode: multi
  validation_2:
    name: val_mdas_proj_dsm_s2
    type: MDASCSVDataset
    path: files/test/mdas_test_affine_projective_pairs/mdas_test_affine_projective_3K_DSM_Sentinel-2.csv
    data_path: data/MDAS/valid
    norm: min-max
    homography: projective
    mode: multi
  validation_3:
    name: val_imagenet_proj_csv
    type: ImageNetCSVDataset
    path: files/valid/imagenet_valid_affine_projective.csv 
    data_path: data/ImageNet/
    norm: min-max
    homography: projective
    mode: mono

model:
  model_name: AligNetModel
  architecture: AligNetViT
  pretrained_encoder_path: "facebook/dinov3-vitl16-pretrain-sat493m"        # "facebook/dinov3-vitl16-pretrain-sat493m" / "facebook/dinov3-vitl16-pretrain-lvd1689m"
  img_size: 336
  input_channels: 1
  attention_heads: 4
  window_size: 16
  num_transform_parameters: 8
  project_embed: false
  use_lora: false

loss:
  type: RegistrationLoss

train:
  num_workers: 3
  freeze_policy: encoder
  batch_size: 70
  epochs: 40
  lr: 0.0001
  momentum: 0.9
  scheduler: ExponentialLR
  scheduler_gamma: 0.99999
  checkpoint_dir: "./experiments"
  checkpoint_path: "checkpoints/affine_imagenet_sat_sensoraug_adapt8.ckpt"   # start from the affine checkpoint adapted to 8 outputs
  checkpoint_interval: 200
  val_interval: 0.2
  log_interval: 50

  losses:
    alpha1: 10
    alpha2: 1
    alpha3: 1

wandb:
  project: alignet
  resume_id: ~
